#!/bin/zsh
echo "Moving old mirrorlist to /etc/pacman.d/mirrorlist.old"
mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.old
echo "Downloading new mirrorlist and saving to /etc/pacman.d/mirrorlist"
curl -s "https://www.archlinux.org/mirrorlist/?country=DE&protocol=http&protocol=https&ip_version=6&use_mirror_status=on" | head -16 | sed 's/^#//' > /etc/pacman.d/mirrorlist
